[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
ast = true
--ffi = true
build-info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
arbitrum-sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
base-sepolia = "https://base-sepolia.drpc.org"
amoy = "https://polygon-amoy.drpc.org"
polygon = "https://polygon-rpc.com"

[etherscan]
80002 = { key = "RSCF1WST8GDYNA42CUSRXSAMWQHTG4YHGQ", url = "https://api.etherscan.io/v2/api?chainid=80002" }
137 = { key = "RSCF1WST8GDYNA42CUSRXSAMWQHTG4YHGQ", url = "https://api.etherscan.io/v2/api?chainid=137" }
421614 = { key = "RSCF1WST8GDYNA42CUSRXSAMWQHTG4YHGQ", url = "https://api.etherscan.io/v2/api?chainid=421614" }
84532 = { key = "RSCF1WST8GDYNA42CUSRXSAMWQHTG4YHGQ", url = "https://api.etherscan.io/v2/api?chainid=84532" }